Functional components refactor
c3c1l1a/Math-Magician pull request #4
Opened 2022-07-08 14:12 UTC by c3c1l1a

The aim of this pull request is to refactor the code to from class components to functional components.

#### What was accomplished
- Added operations to the calculator by lifting events when key is pressed

## Type of change
- New feature

## Checklist

-    [Linting tests](https://github.com/microverseinc/linters-config) pass locally with my changes
-    Used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-    Documentation is done in a [professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

2022-07-08 14:58 UTC, codepantha requested changes
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @c3c1l1a 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/nKN7E76a27Uek/giphy.gif"/>

### Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ Linters passing
✔️ App working as expected

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 14:58 UTC, codepantha commented on src/components/Calculator.js
> +    operation: null,
- [ ] Please use ES6 arrow function syntax for your functional component 🙏

2022-07-08 14:58 UTC, codepantha commented on src/App.js
> +  );
- [ ] Please use ES6 arrow function syntax for your functional component 🙏

2022-07-09 03:38 UTC, mateo951 approved these changes
### Hi @c3c1l1a, 

Well done making the changes requested by the previous reviewer 🤓
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔥 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 03:38 UTC, mateo951 commented on src/App.js
> +);
Addressed ✔

2022-07-13 06:50 UTC, merged